import { Inter } from "next/font/google";
import i18n from '@/utils/i18n.js'
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang={i18n.language}>
      <body>{children}</body>
    </html>
  )
}
